root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
# Config for Linux|macOS
#bin = "./tmp/main"
#cmd = "go build -o ./tmp/main ./cmd/."
#pre_cmd = ["rm -rf ./tmp/main", "chmod -R 755 ./tmp"]
# End config for Linux|macOS

# Config for Windows
bin = "./tmp/main.exe"
cmd = "go build -o ./tmp/main.exe ./cmd/."
pre_cmd = []
# End config for Windows

args_bin = []
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata", ".idea", ".git", ".code"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html", "json"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[proxy]
app_port = 0
enabled = false
proxy_port = 0

[screen]
clear_on_rebuild = false
keep_scroll = true